name: papercups_flutter
description: Native Flutter implementation of the papercups.io chat widget.
version: 3.1.0
homepage: https://github.com/aguilaair/papercups_flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  phoenix_socket: 0.7.2
  http: 1.2.1
  universal_io: 2.2.2
  flutter_markdown: 0.7.1
  timeago: 3.6.1
  intl: 0.18.1 # ignore from web sdk
  file_picker: 8.0.2
  path_provider: 2.1.3
  url_launcher: 6.2.6
  better_open_file: 3.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  build_runner: "2.4.9"
  flutter_lints: 3.0.2
flutter:
