name: papercups_flutter
description: Native Flutter implementation of the papercups.io chat widget.
version: 3.1.0
homepage: https://github.com/aguilaair/papercups_flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  phoenix_socket: 0.6.4
  http: 1.1.0
  universal_io: 2.2.2
  flutter_markdown: 0.6.18
  timeago: 3.6.0
  intl: 0.18.1
  file_picker: 6.1.1
  path_provider: 2.1.1
  url_launcher: 6.2.1
  #  open_file: ^3.2.1
  better_open_file: 3.6.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.2
  build_runner: "2.4.6"
  flutter_lints: 3.0.1
flutter:
